### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by bwvoss** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#16]

**Comment by JoshCheek** [comment]
Just for the record, this is the wonkiest fucking error ever. It probably won't affect us, but I've probably lost over a week of my life to this error.

Anyway, when you have a local var, its also possible that you meant to invoke a method, and Ruby doesn't know which, so it separates NameError from [NoMethodError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/1), but they're pretty similar, except here you'd probably want to also check names of local variables to see if it was a misspelling.

```ruby
a

# ~> NameError
# ~> undefined local variable or method `a' for main:Object
```

**Comment by JoshCheek** [comment]
I think for iteration 2, I'd like to see context before and after. Lets assume 5 lines for now, eventually I'd like to be able to see the containing expression, or 5 lines of code in either direction.
