### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by bwvoss** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#2]

**Comment by JoshCheek** [comment]
Is there more we should do for iteration 1? If not, I'm inclined to close this one, we can open new issues for nuances around them.

**Comment by JoshCheek** [comment]
For iteration 2, I'd like to see context after the first line, of the backtrace (the method definition), and before/after the second line in the backtrace (the caller). Lets assume 5 lines for now, eventually that should be configurable.

I'm going to leave this open for a bit, but it's basically already implemented.
