### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by bwvoss** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#20]

**Comment by JoshCheek** [comment]
Typically user raised, I'd look for the location of the error, any conditionals that would have led to a different path, then why did it go down that path. Would be cool if we could get bindings into the exception and then show them the values of relevant variables.

```ruby
raise 'omg'

# ~> RuntimeError
# ~> omg
```

**Comment by JoshCheek** [comment]
I think for iteration 2, I'd like to see context before and after. Lets assume 5 lines for now, eventually that should be configurable.
