### ISSUE TITLE
SystemExit

### ISSUE THREAD

**Issue by bwvoss** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#27]

**Comment by JoshCheek** [comment]
We shouldn't rescue this one. It's really only an implementation detail that it's an exception. eg I explicitly ignore it in [Seeing Is Believing](https://github.com/JoshCheek/seeing_is_believing/blob/cc93b4ee3a83145509c235f64d9454dc3e12d8c9/lib/seeing_is_believing/event_stream/producer.rb#L85)

**Comment by JoshCheek** [comment]
Closed, as it was handled in Iteration 1
