### ISSUE TITLE
fatal

### ISSUE THREAD

**Issue by bwvoss** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#28]

**Comment by JoshCheek** [comment]
Ohh, this one will be interesting, we'll have to rescue `Exception` to catch it, iirc. I think I only hit it when my program deadlocked. But then I went looking and found a few other places in the source where it comes up (is there any way to query tweets? I tweeted about it back when I was at DCamp). I think they had to do with strange ways to use numeric types. Anyway, this is prob best left for towards the end :)

**Comment by JoshCheek** [comment]
This one looks seems fine for now.

![screenshot 2015-05-31 22 41 36](https://cloud.githubusercontent.com/assets/77495/7906317/42d51f80-07e6-11e5-9267-b7e1013aaee1.png)
