### ISSUE TITLE
Iteration 1 - v0.0.1

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#30]
* [x] Get running on travis for 2.x, <strike>rbx</strike>, <strike>JRuby</strike> ([ref](https://github.com/JoshCheek/thread_order/blob/b738ea22f6d25ce67cc76ed6dfce119b123eee51/.travis.yml))
* [x] Consolidate implementation details into a lib we can reuse and unit test.
* [x] Identify 5 most common / useful errors, for each one, determine what is a good heuristic that doesn't require the implementation to be too comprehensive for now, we'll implement them in iteration 2.
* [x] Have a reasonable default for when there is no heuristic.
* [x] Do not capture [SystemExit](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/27)
* [x] Passing on CI
* [x] Release v0.1

**Comment by JoshCheek** [comment]
@bwvoss want to do the Travis one?

For errors, here are the ones I think are most useful:
* [RuntimeError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/20) (just b/c its so common, [StandardError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/11) is also really common, but it's usually used as a superclass)
* [SyntaxError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/8)
* [LoadError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/6)
* [ArgumentError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/2)
* [NameError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/16) / [NoMethodError](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/1) (NameError is "undefined local variable or method", with NoMethodError, it can tell syntactically that you were intending to call a method and not a local variable, so these are really similar)

**Comment by bwvoss** [comment]
The iteration outline looks good.  Yeah, Ill take the travis build.

**Comment by JoshCheek** [comment]
You good with this list for iteration 2?

**Comment by bwvoss** [comment]
:+1:

**Comment by bwvoss** [comment]
I haven't spent any time looking at the issues with rbx on travis, but I did spend some time with jruby.  Jruby is running against 1.9.3 officially with [their newest release](http://jruby.org/www/2015/01/30/jruby-1-7-19.html).  The JRUBY_OPTS allows us to bump it up to ruby v.2.0.0, but I'm not sure what pitfalls we'll find, and it won't allow us to bump up to 2.1.X/2.2.X.  Some of the features of keyword arguments that we're using were released in ruby 2.1, and that is what's giving us the syntax errors.

The safe bet in the long run is supporting v.1.9.X and newer, but for version 0.1.0 of what-weve-got-here we may just defer jruby support.  Though my vote is to just make it compatible and that should resolve the syntax errors we're seeing when running against jruby (with ruby versions 1.9.3 and 2.0.0), and solve the issue in the long run (though I haven't tested that assumption yet).

**Comment by JoshCheek** [comment]
I'm on board with that.

I did look at the rbx failures, they're due to path issues when asking the source location of a method. We'll have to address that, I don't know how yet, though. It kind of looked like their code calls back into ours, which the MRI code probably does, too, but MRI code probably does it from C level code, so we don't see the intermediate invocations. We may need to just filter the backtrace a bit, not sure.

**Comment by JoshCheek** [comment]
Getting Rbx and JRuby working is going to be really hard :( I've spent quite a while on it already (lots of little hard to identify/diagnose differences), and it's close, but for example, in the ArgumentError, they don't include the line from the method that was called

So, for this code:

```ruby
require 'pp'

module Test
  def self.backtrace1
  end
  def self.backtrace2
    backtrace1 123
  end
end

begin
  Test.backtrace2
rescue ArgumentError
  pp $!.backtrace
end
```

I get these different outputs:

```ruby
$ chruby-exec 2.2 -- ruby proving_grounds/argument_error.rb
["proving_grounds/argument_error.rb:4:in `backtrace1'",
 "proving_grounds/argument_error.rb:7:in `backtrace2'",
 "proving_grounds/argument_error.rb:12:in `<main>'"]


$ chruby-exec jruby -- ruby proving_grounds/argument_error.rb
["proving_grounds/argument_error.rb:7:in `backtrace2'",
 "proving_grounds/argument_error.rb:12:in `(root)'"]


$ chruby-exec rbx -- ruby proving_grounds/argument_error.rb
["proving_grounds/argument_error.rb:7:in `backtrace2'",
 "proving_grounds/argument_error.rb:12:in `__script__'",
 "kernel/delta/code_loader.rb:66:in `load_script'",
 "kernel/delta/code_loader.rb:152:in `load_script'",
 "kernel/loader.rb:645:in `script'",
 "kernel/loader.rb:799:in `main'"]
```

And I'm not really sure how to get that info out of them, b/c it would really require me to have a binding into the exception site, so I could ask for the method that was invoked, and then get its source location off of the method object. I might be able to get that with `set_trace_func`, or its successor, `Tracepoint`, but I'm not sure of the performance implications, and I think it's beyond the scope of our first release.

Any issue with dropping Rbx/Jruby support until we have better abstractions to compensate for the differences?

**Comment by bwvoss** [comment]
Bummer, but I have no issue with that.

**Comment by JoshCheek** [comment]
Pushing the reworking of the formatter into the next sprint. v0.0.1 of the gem is published at https://rubygems.org/gems/what_weve_got_here_is_an_error_to_communicate
