### ISSUE TITLE
Abstraction from ANSI escape codes?

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#32]
Would appreciate any thoughts, @bwvoss.

## An example

Currently, we generate error messages that look like this:

![screen shot 2015-04-06 at 10 26 08 pm](https://cloud.githubusercontent.com/assets/77495/7016905/00595b68-dcac-11e4-9d46-f2041f01385c.png)

The [code](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/blob/dae41af8bbab0f61411669e8337dc5825d356ddb/lib/error_to_communicate/format.rb) that does this formatting is very coupled to ANSI escape sequences, and the terminal. 
Here is a snippet of an made up interface for describing the information we want to format.

```ruby
Format
  .new
  .partition.header { |error_type|
    error_type.title @info.classname
    error_type.subtext.class(:error) { |message|
      message.text @info.explanation
      message.deemphasize { |details|
        details.text('(expected ').stands_out(@info.num_expected)
               .text(', sent '   ).stands_out(@info.num_received)
               .text(')')
      }
    }
  }
  .partition { |heuristic|
    heuristic = display_location formatter:  heuristic,
                                 annotation: "expected #{@info.num_expected}",
                                 location:   @info.backtrace[0],
                                 highlight:  @info.backtrace[0].label,
                                 context:    0..5,
                                 emphasisis: :code

    heuristic = display_location formatter:  heuristic
                                 annotation: "SENT #{info.num_received}",
                                 location:   info.backtrace[1],
                                 highlight:  info.backtrace[0].label,
                                 context:    -5..5,
                                 emphasisis: :code
    heuristic
  }
  .partition { |backtrace|
    info.backtrace.reduce(backtrace) do |formatter, location|
      display_location formatter:  formatter,
                       location:   location,
                       highlight:  location.succ.label,
                       context:    0..0,
                       emphasisis: :path
    end
  }
```

## Motivations

I don't want to render colours directly into the output string, because they become impossible to work with (ansi escape sequences lack abstractions which prevents you from being able to correctly format and colour unless you maintain a virtual terminal screen. I.e. you can't change one part of the output (say highlight a word), because it affects the state of the terminal in ways you can't determine.

I'd also like to be able to semantically specify the information, and then separate the presentation, like CSS does for HTML. This way the error could be rendered to the terminal, or HTML, or really to anything that presents info, so long as we make an adapter for it.

Not sure that this is what I want, but its probably on the right track.

Note that format nodes are immutable, and therefore only ever added onto. This has some implications on the design of the code (eg if you pass it to a method, the method has to return it in order for those changes to take effect).

## Alternatives

* Maybe something that's more data-structurey and less DSLy?
* Are there Ruby DSLs that exist already for specifying semantic structure, which we could just build an adapter for our terminal output? (ie a Ruby abstraction for the DOM could very likely work for us on the terminal, too, and then we don't have to build this). Note: [asked the twitters](https://twitter.com/josh_cheek/status/585299120719409153).

**Comment by ConradIrwin** [comment]
We would love the same thing for @pry.

**Comment by JoshCheek** [comment]
@ConradIrwin can you talk a bit about what Pry is trying to do with it? Ie if I we make it, it would be good for to have other use cases in mind to keep it flexible and useful.

**Comment by bwvoss** [comment]
+1 I really like the idea, and I think there are enough potential use cases to justify the abstractions. From the command line, not all operating systems support ANSI escape codes (like windows).  Practically, not all devs use the command line, or this library could be used for more beginners, and an HTML/CSS display could be much more comfortable for them, so having some really flexible display library would allow the gem to be used in other useful ways.

Were you thinking something like...

```ruby
  Display::Console.new(some_error_configuration).display
  Display::Web.new(some_error_configuration).display
```

We would have to build an adapter for each medium, but they should all be able to talk to the configuration object...

Less likely, because it's mad DSLy, but were you considering generating the display like how [bureaucrat](https://github.com/tizoc/bureaucrat) does it?

**Comment by JoshCheek** [comment]
I'm going to close this for now, there is progress being made [here](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/33#issuecomment-106855337). We'll see where it goes over time, I don't think the top-down approach I tried to use here is going to get me anywhere, better to just see how the existing implementation deals with varying requirements, and then possibly build on top of them.
