### ISSUE TITLE
Fix blog post link

### ISSUE THREAD

**Issue by markburns** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#61]
I was interested in reading the blog post linked to in the README, but the site is down. 

Could you update the link or maybe add the text to the repo?

**Comment by JoshCheek** [comment]
Hi, fixed it. For easy reference, the link is: [https://www.turing.io/blog/2015/01/18/what-weve-got-here-error-communicate](https://www.turing.io/blog/2015/01/18/what-weve-got-here-error-communicate)

**Comment by markburns** [comment]
Nice, thanks.

Interesting read and great idea.
