### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by bwvoss** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#8]

**Comment by JoshCheek** [comment]
Some are simple enough, it basically knows what is wrong and where to look

```ruby
1 1

# !> Syntax Error: :1
# !> unexpected token tINTEGER
```

Others are harder, like if you forget to match a do/end pair, then it gets to the end of the file and realizes that something didn't get closed, but doesn't really know which one. Identifying that second one should be pushed back, probably, it will take some thought and probably won't work in all cases (eg if you go based on indentation, then quirks in how people indent their code can mess it up, or newbs who have inconsistent indentation can mess it up).

**Comment by JoshCheek** [comment]
I think for iteration 2, I'd like to see context before and after. Lets assume 5 lines for now, eventually it would be nice to show the complete expression (so parsing the code, identifying its expression, and then focusing on just enough to understand where it is in the code, and where specifically within that line.
